### ISSUE TITLE
Homey incompatible

### ISSUE THREAD

**Issue by Povlov** [casperboone/homey-sony-srs-multiroom-speakers#2]
I am still on 1.3.1.
The app will not install because of that. Do I need to go to 1.5.3 to  be able to install this app?

**Comment by casperboone** [comment]
Yes, the app only supports >= v1.5 😉.

**Comment by Povlov** [comment]
Installed 1.5.3, and the Sony App..
Two nice speakers w/ good deal of connection choices. Easy setup. The app just makes automation just a little better. "When TV On switch input to Audio In"
(cannot get HDMI ARC working on Samsung UE42F5500 TV; which is probably not HDMI ARC although manual mentions capability.)

**Comment by casperboone** [comment]
@Povlov Good to hear! 😄
