### ISSUE TITLE
Not possible to add a device.

### ISSUE THREAD

**Issue by Povlov** [casperboone/homey-sony-srs-multiroom-speakers#4]
After new installation of your app I can not add a device.
This is not a new issue, just I kind reminder to ask you to have a look?

**Comment by casperboone** [comment]
@Povlov Which device (type) are you trying to add?

**Comment by Povlov** [comment]
Hi Casper.
The SRS ZR5 speaker. I had it connected just fine, but after some update (of the Sony speaker firmware) long ago it failed. I removed the device, reinstalled the app., but bo luck.
The previously mentioned 
"Cannot read property '0' of undefined
Je mag dit venster sluiten."
![screenshot 2018-06-19 at 17 34 51](https://user-images.githubusercontent.com/24312420/41607788-22ac9038-73e7-11e8-805c-04da3796e49a.png)

I am on Homey Firmware 1.5.8
Cheers, hope you can check for me!

**Comment by casperboone** [comment]
Hm okay, I haven't updated mine yet. So the issue might indeed be speaker firmware related. Thanks for the info. I'll try to look into it asap :)

**Comment by Povlov** [comment]
Did you have a look, Casper?

**Comment by ejimaging** [comment]
Hi Casper, i tried to add my Sony srs-xb31 but homey does not find the device can you help me please thnx kind regards Eric.

**Comment by casperboone** [comment]
Unfortunately I cannot reproduce the issue. The app still seems to work fine here. This might be because my speakers are on older firmware, however I was not able to update them (at least not from the Sony app).

@Povlov I'm assuming you see this error after selecting your device and clicking next? Maybe we can schedule a Teamviewer session which allows me to debug in your specific situation.

**Comment by Povlov** [comment]
Thanks for responding!!
I revert here shortly.



Peter de Vries


Op zo 6 jan. 2019 om 17:21 schreef Casper Boone <notifications@github.com>:

**Comment by Povlov** [comment]
Casper, the speaker(s) can best be updated with the update button which is on the speaker.
Please check detailed instructions here: 
https://helpguide.sony.net/speaker/srs-zr5/v1/en/contents/TP0001150220.htm

Most likely you will be able to reproduce the error a the current users reported here.
It really is nothing more then a unable to connect with a screen as above. This persists after a remove/fresh reinstall of your app..

I am really looking forward to a working version, i hope youwill be able to get things working!

Betterlink: 

https://www.sony.com/electronics/support/portable-speakers-srs-series/srs-zr5#/downloadTab

**Comment by casperboone** [comment]
@Povlov I already looked into it a bit more, but apparently my speakers are on the latest firmware, so that's not the issue here 🙈.

 Let me see if I can add some clearer error reporting that will help us figure out the issue.

**Comment by anom123** [comment]
@Povlov I've tried reproducing this, but my ZR5 connects fine. What I mean is that I can add under devices and then e.g. use it as a target destination in a flow. Could it not that e.g. the Smartphone app locked a mandatory configuration parameter obstructing the Homey to own it? If you don't have a huge setup for it I'd try to factory default the ZR5 (initializing via power and minus button as described: https://helpguide.sony.net/speaker/srs-zr5/v1/en/contents/TP0001038371.html).
After pairing mine, I created a flow and was able to change the Source from Network to USB to proof it actually works. I'm on Homey 1.5.13 and Sony Homey app 0.0.1 and ZR5 Firmware 5.0.3.2111

**Comment by Povlov** [comment]
Casper, I recently changed to V2. Many flows and devices had to be altered or redone; I guess that must have been so.
So after all that, I reset the speaker as per your advice.
After that, adding it as a device again in Homey works fine!
Yet to test this with some (lonng deactivated) flows, but confident that will work too!
Tx, mate!
