### ISSUE TITLE
Invalid device class

### ISSUE THREAD

**Issue by jeroenvollenbrock** [casperboone/homey-sony-srs-multiroom-speakers#5]
Hi Casper, 

This app uses the device class "speakers" instead of "speaker". I'm not sure how this got through the appstore validation process, as "speakers" is not a valid device class. This is causing problems when installing this app on upcoming homey version v2.0.0. Could you please update your app.json to use "speaker" as device class instead and submit a new version to ensure this app remains functional?

**Comment by casperboone** [comment]
@jeroenvollenbrock ❤️for letting me know, will look into it :)
